from AOC_Lib.pqueue import PQueue

if __name__ == "__main__":
    q = PQueue()
    q.push("Apple", 0)
    q.push("Banana", 0)
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("Banana", 0)
    q.push("Apple", 0)
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("Apple", 0)
    q.push("Banana", 0)
    q.push("Apple", 0)
    q.push("Banana", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("Banana", 0)
    q.push("Apple", 0)
    q.push("Banana", 0)
    q.push("Apple", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("Apple", 0)
    q.push("Banana", 0)
    q.push("Banana", 0)
    q.push("Apple", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("Banana", 0)
    q.push("Apple", 0)
    q.push("Apple", 0)
    q.push("Banana", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("A", 0)
    q.push("B", 0)
    q.push("C", 0)
    q.push("D", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))

    q.push("D", 0)
    q.push("C", 0)
    q.push("B", 0)
    q.push("A", 0)
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(q.popMin())
    print(len(q))